### ISSUE TITLE
Sqlite incompatible - migration syntax

### ISSUE THREAD

**Issue by imanghafoori1** [cmgmyr/laravel-messenger#77] opened 2015-09-20 15:38 UTC
It seems , the hard coding sql syntax like this : 
  public function up()
    {
        DB::statement('ALTER TABLE `'.DB::getTablePrefix().'participants` CHANGE COLUMN `last_read` `last_read` timestamp NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP;');
    }
in the 2014_11_10_083449_add_nullable_to_last_read_in_participants_table.php file.
causes syntax error when using sqlite. it should be translated to the equivalent php methods.

**Comment by cmgmyr** [comment] 2015-09-20 16:17
Thanks for reporting, I'm still looking in to this - duplicate of #57. I'm hoping to get this resolved shortly.

**Closed by cmgmyr** 2015-09-20 16:17 UTC
Labels: duplicate
